services:
  redis-server:
    image: redis:6.2
    ports:
      - "6379:6379" # Default Redis Port
    # Add any other required services for your Redis deployment
  webapp:
    build: .
    ports:
      - "8080:8080" 
    depends_on:
      - redis-server 